### ISSUE TITLE
Visibility pane doesn't show

### ISSUE THREAD

**Issue by pixolin** [epiphyt/block-control#8]
After activating the plugin in a plain vanilla WordPress test installation (theme Twenty Twenty, no other plugins used), I miss the visibility pane:

![screenshot_000284@2x](https://user-images.githubusercontent.com/1968542/177759636-f345a094-2a2e-4db1-b29f-de6f442b983d.png)

The plugin is not usable for me because of this.

**Comment by MatzeKitt** [comment]
Is there any error message in the browser console?

Can you please try replacing the file in `/wp-content/plugins/block-control/build/index.asset.php` with the following content?

```php
<?php return array('dependencies' => array('wp-block-editor', 'wp-components', 'wp-compose', 'wp-data', 'wp-date', 'wp-element', 'wp-hooks', 'wp-i18n'), 'version' => '461dca8aa1b2634ef8ab85b5070be329');
```

**Comment by pixolin** [comment]
Changing the code as suggested doesn't solve the issue for me. 

With that code, my browser shows an error message 

```
Uncaught TypeError: Cannot destructure property 'InspectorControls' of 'wp.editor' as it is undefined.
    at 187 (index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:1480)
    at l (index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:11068)
    at index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:12225
    at l.O (index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:11365)
    at index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:12239
    at index.js?ver=461dca8aa1b2634ef8ab85b5070be329:1:12244
```

however, without the code change, I get following error:

```
index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1 Uncaught TypeError: Cannot destructure property 'createHigherOrderComponent' of 'wp.compose' as it is undefined.
    at 187 (index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:1379)
    at l (index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:11068)
    at index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:12225
    at l.O (index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:11365)
    at index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:12239
    at index.js?ver=1798232e080a9dec3a587bd8c812c1fa:1:12244
```

**Comment by pixolin** [comment]
I forgot to mention, version 1.0.3 displays the visibility pane (although I'm missing the time setting there).

**Comment by MatzeKitt** [comment]
Thank you, I could reproduce the issue in a fresh installation. There is something wrong with the dependencies not properly loaded. I switched to proper imports in #9 to address this issue, which should also resolves yours.

**Comment by pixolin** [comment]
Sounds great. Thank you. 
You want me to report back as soon as I can update the plugin?

**Comment by MatzeKitt** [comment]
That would be great!

You can also try the attached package.
[block-control.zip](https://github.com/epiphyt/block-control/files/9063962/block-control.zip)

**Comment by pixolin** [comment]
Thank you for handling this issue so fast. 👍🏼
